config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('articles.urls', 'config'), namespace='articles')),
    path('users/', include(('users.urls', 'config'), namespace='users'))
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out')

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.forms import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Create any username')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Enter password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Repeat password')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Enter your username')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Enter password')

    class Meta:
        model = User
        fields = ['username', 'password']

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


# Create your views here.
from users.forms import SignUpForm, SignInForm


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:sign_in')
    form = SignUpForm()
    return render(request, 'sign_up.html', {
        'form': form
    })


def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('articles:articles')
    form = SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block content %}
    <form class="has-text-centered site-form has-background-light" method="post">
        <h1 class="title is-size-2 has-text-centered">Sign in</h1>
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button class="button is-success is-fullwidth mt-4" type="submit">Sing in</button>
        <p class="content mt-3">
            Don't have an account?
            <span>
                <a href="{% url 'users:sign_up' %}">Sign up here</a>
            </span>
        </p>
    </form>

{% endblock %}

users/templates/sign_up.html
{% extends 'base_layout.html' %}
{% block content %}
    <form class="site-form has-text-centered has-background-light" method="post" style="margin-top: 120px">
        <h1 class="title is-size-2 has-text-centered has-text-black">Sign up</h1>
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="button is-primary is-fullwidth mt-3">Sign up</button>
        <p class="content mt-3">
            Already have an account?
            <span>
        <a href="{% url 'users:sign_in' %}">Sign in here</a>
    </span>
        </p>
    </form>
{% endblock %}