articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('articles/', views.articles, name='articles'),
    path('aricle_create/', views.article_create, name='article_create'),
    path('<slug>/', views.article_detail, name='article_detail'),
    path('edit_article/<slug>', views.edit_article, name='edit_article'),
    path('delete_article/<slug>', views.delete_article, name='delete_article'),
    path('<slug>/like', views.like, name='like'),
    path('<slug>/dislike', views.dislike, name='dislike'),
    path('delete/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('<slug>/comment/<pk>/edit/', views.edit_comment, name='edit_comment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('articles.urls', 'config'), namespace='articles')),
    path('users/', include(('users.urls', 'config'), namespace='users'))
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out')

]

articles/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField(null=True)
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    thumb = models.ImageField(default='image.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')

    def __str__(self):
        return self.title

    def snippet(self):
        return self.text[:20] + '... read more'

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.article} - {self.body[:5]}"

articles/forms.py
from django import forms
from . import models


class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    text = forms.CharField(widget=forms.TextInput(attrs={'class': 'textarea', 'size': '40'}))
    slug = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = models.Article
        fields = ['title', 'text', 'slug', 'thumb', 'author']


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Write your comment here...'
    }))

    class Meta:
        model = models.Comment
        fields = ['body', ]

articles/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from articles import forms
from articles.forms import CommentForm
from articles.models import Article, Comment


@login_required(login_url='/users/sign-in/')
def articles(request):
    article = Article.objects.all().order_by('date')
    search = request.GET.get('search')
    article = article.filter(Q(title__icontains=search) |
                             Q(text__icontains=search)) if search else article
    return render(request, 'articles.html', {
        'article': article,
    })


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    form = CommentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.article = article
        instance.save()
        return redirect('articles:article_detail', slug=article.slug)
    return render(request, 'article_detail.html', {
        'article': article,
        'form': form,
    })


@login_required(login_url='/users/sign-in/')
def article_create(request):
    form = forms.ArticleForm(request.POST or None, request.FILES)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('articles:articles')
    return render(request, 'article_create.html', {'form': form})


@login_required(login_url='/users/sign-in/')
def edit_article(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.user != article.author:
        return render(request, 'error.html', {'article': article})
    form = forms.ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=request.POST.get('slug'))
    return render(request, 'edit_article.html', {
        'article': article,
        'form': form
    })


def delete_article(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:articles')
    return render(request, 'delete_article.html', {'article': article})


def like(request, slug):
    article = get_object_or_404(Article, slug=slug)

    if request.user not in article.likes.all():
        article.likes.add(request.user)
        article.dislikes.remove(request.user)
    elif request.user in article.likes.all():
        article.likes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)


def dislike(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user not in article.dislikes.all():
        article.dislikes.add(request.user)
        article.likes.remove(request.user)
    elif request.user in article.dislikes.all():
        article.dislikes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user != comment.user:
        return render(request, 'error.html', {'comment': comment})
    if request.method == 'POST':
        comment.delete()
        return redirect('articles:article_detail', slug=comment.article.slug)
    return render(request, 'delete_comment.html', {'comment': comment})


def edit_comment(request, slug, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user != comment.user:
        return render(request, 'error.html', {'comment': comment})
    form = forms.CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=slug)
    return render(request, 'edit_comment.html', {
        'form': form,
        'article': comment.article
    })

articles/templates/article_create.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light" method="post" action="{% url 'articles:article_create' %}" enctype="multipart/form-data">
   {% csrf_token %}
   {{form}}
   <div class="has-text-centered my-2">
       <button type="submit" class="button is-success">Отправить</button>
       <a href="{% url 'articles:articles' %}" class="button is-danger">Отмена</a>
   </div>
</form>
{% endblock %}

articles/templates/article_detail.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <div class="box" style="min-width:100%">
        {% if user == article.author %}
            <div class="has-text-right">
                <a href="{% url 'articles:edit_article' article.slug %}" class="button is-info ">
                    <ion-icon name="create-outline"></ion-icon>
                </a>
                <a href="{% url 'articles:delete_article' article.slug %}" class="button is-danger">
                    <ion-icon name="trash-outline"></ion-icon>
                </a>
            </div>
        {% else %}
            <div class="has-text-right">
                <p class="content has-text-grey-light">
                    You can't not edit and delete this post
                </p>
            </div>
        {% endif %}
        <div class="title has-text-dark has-text-centered">{{ article }}</div>
        <img src="{{ article.thumb.url }}" alt="" class="image is-centered" style="min-width: 100%; border-radius: 5px">
        <div class="subtitle has-text-dark has-text-centered">{{ article.text }}</div>
        {% if user not in article.likes.all and user not in article.dislikes.all %}
            <div class="columns">
                <div class="column is-1">
                    <form action="{% url 'articles:like' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button">
                            <ion-icon name="thumbs-up-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_likes }}</span>
                        </button>
                    </form>
                </div>
                <div class="column is-1">
                    <form action="{% url 'articles:dislike' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button">
                            <ion-icon name="thumbs-down-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_dislikes }}</span>
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if user in article.likes.all and user not in article.dislikes.all %}
            <div class="columns">
                <div class="column is-1">
                    <form action="{% url 'articles:like' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button is-success">
                            <ion-icon name="thumbs-up-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_likes }}</span>
                        </button>
                    </form>
                </div>
                <div class="column is-1">
                    <form action="{% url 'articles:dislike' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button">
                            <ion-icon name="thumbs-down-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_dislikes }}</span>
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if user not in article.likes.all and user in article.dislikes.all %}
            <div class="columns">
                <div class="column is-1">
                    <form action="{% url 'articles:like' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button">
                            <ion-icon name="thumbs-up-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_likes }}</span>
                        </button>
                    </form>
                </div>
                <div class="column is-1">
                    <form action="{% url 'articles:dislike' article.slug %}" method="post"
                          class="has-text-right">
                        {% csrf_token %}
                        <button type="submit" name="article_id" value="{{ article.id }}"
                                class="button is-danger">
                            <ion-icon name="thumbs-down-outline"></ion-icon>
                            <span class="ml-2">{{ article.total_dislikes }}</span>
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if not article.comment_set.all %}
            <div class="has-text-centered has-text-grey-light is-5 mx-3">
                No comments yet. Be first to leave comment...
            </div>
        {% else %}
            <p class="has-text-centered is-size-3 mb-6">Comments</p>
            {% for comment in article.comment_set.all %}
                <article class="message is-info">
                    <div class="message-header">
                        {% if user == comment.user %}
                            Added by you at {{ comment.date_added }}
                        {% else %}
                            Added by {{ comment.user }} at {{ comment.date_added }}
                        {% endif %}
                        {% if user == comment.user %}
                            <div class="has-text-right is-size-5">
                                <a href="{% url 'articles:edit_comment' slug=article.slug pk=comment.pk %}"
                                   class="button is-info">
                                    <ion-icon name="create-outline"></ion-icon>
                                </a>
                                <a href="{% url 'articles:delete_comment' pk=comment.pk %}"
                                   style="text-decoration: none">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="message-body">{{ comment.body }}</div>
                </article>
            {% endfor %}
        {% endif %}
        <div class="has-text-grey is-size-6 has-text-right is-italic">
            <p class="datetime">Date of publication: {{ article.date }}</p>
            {% if user == article.author %}
                <p class="content">Published by you</p>
            {% else %}
                <p class="content">Published by: {{ article.author }}</p>
            {% endif %}
        </div>
        <form method="POST" enctype="multipart/form-data" class="comment">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="button is-success mt-3 is-fullwidth">Submit</button>
        </form>
    </div>
{% endblock %}

articles/templates/articles.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}


    <div class="hero-body">

        <div class="container">
            <div class="columns is-centered is-multiline">
                {% for item in article %}
                    <div class="column is-3">
                        <a href="{% url 'articles:article_detail' item.slug %}">
                            <div class="card has-background-light has-text-centered">
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="title has-text-dark is-2">
                                                {{ item }}
                                            </p>
                                            {% if user == article.author %}
                                                <p class="subtitle is-4 has-text-grey">by you</p>
                                            {% else %}
                                                <p class="subtitle is-4 has-text-grey">by {{ article.author }}</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="content ">
                                        {{ item.snippet }}
                                        <br>
                                        <div>{{ item.date }}</div>
                                        <div class="columns">
                                            <div class="column is-2">
                                                <div class="columns is-gapless">
                                                    <div class="column">
                                                        <ion-icon name=  "thumbs-up-outline" class="mt-1"></ion-icon>
                                                    </div>
                                                    <div class="column">
                                                        <span class="ml-2">{{ item.total_likes }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="column is-2">
                                                <div class="columns is-gapless">
                                                    <div class="column">
                                                        <ion-icon name="thumbs-down-outline"
                                                                  class="mt-1"></ion-icon>
                                                    </div>
                                                    <div class="column">
                                                        <span class="ml-2">{{ item.total_dislikes }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

articles/templates/base_layout.html
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
<section class="hero is-success is-fullheight">
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{% url 'articles:articles' %}">
                        <img src="{% static 'images/monday.svg' %}" width="100" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>

                <div class="navbar-start">
                    {% if user.is_authenticated %}
                        <span class="navbar-item">
                           <a href="{% url 'articles:article_create' %}" class="button is-info is-outlined is-inverted">
                               <span class="mr-2">
                                   <ion-icon name="book-outline"></ion-icon>
                               </span>
                               <span>
                                   Создать пост
                               </span>
                           </a>
                       </span>
                    {% endif %}
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                        {% if user.is_authenticated %}
                            <form action="{% url 'articles:articles' %}" method="get">
                                <div class="field has-addons mt-4 mr-2">
                                    <div class="control">
                                        <input class="input" type="search" placeholder="Find an article" name="search">
                                    </div>
                                    <div class="control">
                                        <button class="button is-primary" type="submit">
                                            Search
                                        </button>
                                    </div>
                                </div>
                            </form>
                            <a class="navbar-item button my-4 mx-1">
                                Welcome : {{ user }}
                            </a>
                            <span class="navbar-item">
                                <a href="{% url 'users:sign_out' %}" class="button is-warning">Sing out</a>
                            </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
    </div>
    {% block content %}
    {% endblock %}
</section>
</body>
</html>

articles/templates/delete_article.html
{% extends 'base_layout.html' %}

{% block content %}
    <form method="post" class="site-form has-background-light" style="margin-top: 200px">
        {% csrf_token %}
        <p class="content has-text-centered is-size-4 mb-4">Are you sure to delete post "{{ article }}"?</p>
        <div class="has-text-centered">
            <button type="submit" class="button is-primary">Yes</button>
            <a href="{% url 'articles:article_detail' article.slug %}" class='button is-danger'>No</a>
        </div>
    </form>
{% endblock %}

articles/templates/delete_comment.html
{% extends 'base_layout.html' %}

{% block content %}
   <form method="post" class="site-form has-background-light">
       {% csrf_token %}
       <p class="content is-size-4 mb-4">Вы действительно хотите удалить комментарий?</p>
       <div class="has-text-centered">
           <button type="submit" class="button is-primary">Подтвердить</button>
           <a href="{% url 'articles:article_detail' comment.article.slug %}" class='button is-danger'>Отмена</a>
       </div>
   </form>
{% endblock %}

articles/templates/edit_article.html
{% extends 'base_layout.html' %}

{% block content %}
    <form class="site-form has-background-light" method="post" enctype="multipart/form-data">
        <h2 class="title is-size-2 has-text-centered">Update Article</h2>
        {% csrf_token %}
        {{ form }}
        <div class="has-text-centered my-4">
            <button class="button is-success" type="submit">Submit</button>
            <a href="{% url 'articles:article_detail' article.slug %}" class="button is-danger ">
                Back
            </a>
        </div>
    </form>
{% endblock %}

articles/templates/edit_comment.html
{% extends "base_layout.html" %}

{% block content %}
    <form class="site-form has-background-light" method="post" enctype="multipart/form-data">
        <div class="title">Edit Comment</div>
        {% csrf_token %}
        {{ form }}
        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success">Отправить</button>
            <a href="{% url 'articles:article_detail' article.slug %}" class="button is-danger">Отмена</a>
        </div>
    </form>
{% endblock %}

articles/templates/error.html
{% if article %}
   <div class="title">Вы не можете удалить или изменить данный пост, так как вы не являетесь
       автором
       этого поста
   </div>
   <a href="{% url 'articles:home' %}" class="button is-success is-fullwidth">
       Вернутся на главную
   </a>
{% else %}
   <div class="title is-4">Вы не можете удалить или изменить данный комментарий, так как вы не являетесь
       автором этого комментария
   </div>
   <a href="{% url 'articles:article_detail' comment.article.slug %}" class="button is-success is-fullwidth">
       Вернутся на страницу поста
   </a>
{% endif %}